openapi: "3.0.0"
info:
  version: 1.0.0
  title: Medical Report
  description: BMI and Helth Risk Report of Users
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://localhost:300/report
paths:
  /:
    get:
      summary: List all report
      operationId: listReport
      tags:
        - report
      responses:
        200:
          description: List of BMI and Risk of Users
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Reports"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Report:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Reports:
      type: array
      items:
        $ref: "#/components/schemas/Report"
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string